version: "3"
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/server
    networks:
      - server

networks: 
  server:
    driver: bridge